# Generated by Django 2.1.15 on 2022-06-27 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyGoals',
            fields=[
                ('goal_name', models.CharField(max_length=150)),
                ('goal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_by', models.CharField(max_length=150)),
                ('moved_by', models.CharField(max_length=150)),
                ('owner', models.CharField(max_length=150)),
                ('goal_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_name+', to='busayoscrummy.GoalStatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_by', models.CharField(max_length=150)),
                ('created_by', models.CharField(max_length=150)),
                ('moved_from', models.CharField(max_length=150)),
                ('moved_to', models.CharField(max_length=150)),
                ('time_of_action', models.CharField(max_length=150)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goal_name+', to='busayoscrummy.ScrumyGoals')),
            ],
        ),
    ]
