# Generated by Django 2.1.15 on 2022-07-06 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busayoscrummy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='busayoscrummy.GoalStatus'),
        ),
        migrations.AlterField(
            model_name='scrumyhistory',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='busayoscrummy.ScrumyGoals'),
        ),
    ]
